#!/bin/bash
### BEGIN INIT INFO
# Provides: procallator
# Required-Start: $local_fs $network $remote_fs
# Required-Stop: $local_fs $network $remote_fs
# Default-Start:  2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: start and stop service procallator
# Description: generates orca system graph rrd files
### END INIT INFO

# This script starts procallator.pl for collection of performance data


id=`ps -e -o pid -o args | grep procallator.pl | grep -v grep | awk '{print $1}'`

case "$1" in
  start)
        # Start procallator
        if [ -n "$id" ]; then
                echo "procallator is already running"
                exit
        fi

        echo -n  "Starting procallator... "

	/usr/local/bin/procallator.pl &      
        echo "Done"
        ;;
  stop)
        # Stop procallator
        if [ -n "$id" ]; then
                echo -n "Stopping proccallator... "
                kill $id        
                echo "Done"
        fi
        ;;
  restart)
        $0 stop
        $0 start
        ;;
  *)
        echo "Usage: procallator {start|stop|restart}"
        exit 1
esac

